spring:
    data:
        mongodb:
            uri: mongodb+srv://${env.MONGO_USER}:<${env.MONGO_PASSWORD}>@${env.MONGO_CLUSTER}/?retryWrites=true&w=majority
            database: ${env.MONGO_DATABASE}